project_id = "eavnxrimrygwaqwbwqge"

[functions.generate-quiz]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.send-daily-email]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false
